### ISSUE TITLE
Add Cova to CLI library list.

### ISSUE THREAD

**Issue by p7r0x7** [zigcc/awesome-zig#17]
Commands, Options, Values, and Arguments by @00jciv00 will be Zig's flagship comptime CLI builder for years to come: https://github.com/00JCIV00/cova

**Comment by jiacai2050** [comment]
Also, if you want to add it to this list, please submit a PR.

**Comment by p7r0x7** [comment]
> > Zig's flagship comptime CLI builder
> 
> I wonder how you came to this conclusion...

For months now I've been working with the developer to enrich it's customizability and robustness, but from the beginning I could tell it was a well-made piece of software. That's my background on this.

**Comment by 00JCIV00** [comment]
> > Zig's flagship comptime CLI builder
> 
> I wonder how you came to this conclusion...

Hey, I think @p7r0x7 is being very gracious with their words here. They've been a great help in testing and coming up with ideas, and are deservedly passionate about the project. Ultimately Cova is a library that I've put a lot of effort into in hopes of making it as robust and easy to use as possible.

I didn't know about this list previous to this. It would be great if I can get Cova on here and if a PR is the right way of doing that, I'll proceed accordingly. Appreciate the guidance!

**Comment by jinzhongjia** [comment]
why not create a pull request ?

**Comment by 00JCIV00** [comment]
> why not create a pull request ?

I was away for a bit. Just submitted a PR (2940397424163eedd44a2331370b1c88539601af). Thank you!
