### ISSUE TITLE
Proposal to extend list of date/time packages

### ISSUE THREAD

**Issue by FObersteiner** [zigcc/awesome-zig#21]
since this seems to be the most up-to-date version of awesome-zig, I'm making this proposal here :)

### date / time

we could add:

- [travisstaloch/date-zig](https://github.com/travisstaloch/date-zig) : fast calendar algorithms ported to Zig (Cassio Neri's [EAF](https://github.com/cassioneri/eaf))
- [leroycep/chrono-zig](https://github.com/leroycep/chrono-zig) : Zig port of the Rust chrono crate
- [karlseguin/zul](https://github.com/karlseguin/zul) : some date/time handling functionality among the other useful stuff

### timezones

we could also extend "Date and Time" to "Date, Time and Timezones":

- [leroycep/zig-tzif](https://github.com/leroycep/zig-tzif) : [TZif](https://datatracker.ietf.org/doc/html/rfc8536) parser that also handles POSIX timezone strings

**Comment by jiacai2050** [comment]
Sounds good to me, welcome to open an PR.

**Comment by FObersteiner** [comment]
> Sounds good to me, welcome to open an PR.

done, see PR #22. I wasn't sure if we should make subsections for date/time and timezones. At the moment, I think it is best to have all the packages in one date/time/timezones section.

**Comment by jiacai2050** [comment]
> At the moment, I think it is best to have all the packages in one date/time/timezones section.

Agreed.
